"""Listas de raças para dropdown no frontend."""

DOG_BREEDS = [
    "SRD (Sem Raça Definida)",
    "Akita",
    "Basset Hound",
    "Beagle",
    "Bichon Frisé",
    "Border Collie",
    "Boxer",
    "Buldogue Francês",
    "Buldogue Inglês",
    "Bull Terrier",
    "Cavalier King Charles",
    "Chihuahua",
    "Chow Chow",
    "Cocker Spaniel",
    "Dachshund (Teckel)",
    "Dálmata",
    "Dobermann",
    "Dogo Argentino",
    "Fila Brasileiro",
    "Fox Paulistinha",
    "Golden Retriever",
    "Husky Siberiano",
    "Jack Russell Terrier",
    "Labrador Retriever",
    "Lhasa Apso",
    "Maltês",
    "Pastor Alemão",
    "Pastor Australiano",
    "Pastor Belga",
    "Pequinês",
    "Pinscher Miniatura",
    "Pit Bull",
    "Poodle",
    "Pug",
    "Rottweiler",
    "Schnauzer",
    "Shar-Pei",
    "Shih Tzu",
    "Spitz Alemão (Lulu da Pomerânia)",
    "Weimaraner",
    "West Highland White Terrier",
    "Yorkshire Terrier",
]

CAT_BREEDS = [
    "SRD (Sem Raça Definida)",
    "Abissínio",
    "Angorá",
    "Bengal",
    "British Shorthair",
    "Burmês",
    "Chartreux",
    "Devon Rex",
    "Exótico",
    "Himalaio",
    "Maine Coon",
    "Munchkin",
    "Norueguês da Floresta",
    "Persa",
    "Ragdoll",
    "Russian Blue",
    "Savannah",
    "Scottish Fold",
    "Siamês",
    "Siberiano",
    "Sphynx",
    "Turkish Van",
]
